CREATE DATABASE StudentSystem;
USE StudentSystem;

CREATE TABLE students (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id VARCHAR(20) NOT NULL UNIQUE,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL,
  course VARCHAR(50) NOT NULL,
  year_level VARCHAR(50) NOT NULL,
  section VARCHAR(50) NOT NULL,
  status VARCHAR(20) DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO students (student_id, first_name, last_name, email, course, year_level, section, status) VALUES
('2025129544', 'Marlon Robrigado', 'ABILO', 'marlon.robtigado@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025102009', 'Kenneth Jhay Haojao', 'AGUILAR', 'kenneth.aguilarjh@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025105180', 'Eric John Garo', 'ANCHETA', 'ejg.ancheta18@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025108691', 'Jhon Cairo Espanta', 'AZARCON', 'jcazarcon@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025104253', 'John Mark Dinglasan', 'BALANAY', 'johnmarkbalanay@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025108361', 'Gian Carlo Roa', 'BERNABE', 'gianroa836@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025128947', 'Jerold Bong-ao', 'BIÑAS', 'jeroldbinas@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025116435', 'Ashton Jake Gacho', 'BROZAS', 'ashtonbrozas64@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2023141428', 'Carl Kevin Aguisanda', 'BUCAYU', 'carlkevin.bucayu@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025104823', 'John Russel O', 'CARBA', 'russelcarba23@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025111720', 'Alexis Jay Lagutang', 'CERENEO', 'alexislagutang@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('20251830', 'Jose Emmanuel Gabion', 'DAVE', 'jegabion83@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025112387', 'Ian James Mandapat', 'DELA CRUZ', 'ianmandapat@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025119046', 'John Benedict Cao', 'DELOS SANTOS', 'johnbenedict.cao@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025110283', 'Raine Benedict Vuel', 'DELOS SANTOS', 'rbv.santos@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025110223', 'Tristan Jeff Brazal', 'GABRIEL', 'tristanjeffb@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025104133', 'Jello Gadong', 'GARDOSE', 'jellogardose13@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025104193', 'John Clyde A.', 'GATBONTON', 'johnclyde.gatbonton@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025111090', 'Zareen Ethel Jumantoc', 'GERONIMO', 'zareengeronimo@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025108421', 'Richard Rabulan', 'GESTOPA', 'richgestopa21@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025116975', 'Terrence Nathaniel Seva', 'LANGGOY', 'terenceseva@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2024129486', 'Jericho Rex Bugal', 'LASTOMEN', 'jerichobugal86@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025114661', 'John Davin Alia', 'LU', 'johndavinlu@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025114631', 'Paolo Tomas', 'MACEDA', 'paolomaceda31@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('20242413', 'Tristan Jay Gabriel', 'MAGALLANES', 'tristangabriel.m@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025108139', 'Carl', 'MAMITES', 'carlmamites@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025116124', 'Benjamin Jr. Calin', 'MANALILI', 'bjcalin36@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025102553', 'Emmanuel', 'MARRON', 'emmanmarron@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025112023', 'Deechmar Badajos', 'ORTIZ', 'deechmar.badajos@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025102839', 'Luiji Roxas', 'PAGUIO', 'luijiroxas03@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025119564', 'Mark Cabrejas', 'PALMA', 'makcabrejas@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025111306', 'Stephen Laxamana', 'PANGILINAN', 'stephenlaxaman28@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025115201', 'Mark Tristan Capilo', 'PUNO', 'marktristan.capilo@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025111814', 'Levi P', 'REYES', 'levireyes.p@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025118749', 'Luis Bernard Gormate', 'REYES', 'bernardgormate95@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025110190', 'Harvey Quindoza', 'RICAFRENTE', 'harveyquindoza@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025121200', 'Francis Kevin Betiz', 'SAN JOSE', 'fkbetiz89@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025112211', 'Merrick', 'SARMIENTO', 'merrick.sarmiento@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025104231', 'Nhibe', 'VILLAHERMOSA', 'nhibe.villahermosa@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active'),
('2025116521', 'Christian Samper', 'VILLANUEVA', 'christiansamper91@gmail.com', 'BSMT', '1st Year', 'MTJ2-B2', 'Active');

INSERT INTO students (student_id, first_name, last_name, email, course, year_level, section, status) VALUES
('202530007', 'Mikko Catampongan', 'PINEDA', 'mikko.pineda@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530075', 'Keith Andrew Cantoria', 'GEGANTOCO', 'keith.gegantoco@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530082', 'Kristine Ericka Gavino', 'FUMIO', 'kristine.fumio@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530130', 'Paul Eleazar Punay', 'AMORES', 'paul.amores@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530147', 'Michael Angelo Esteban', 'MANUEL', 'michael.manuel@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530193', 'Jimler Gablines', 'TAGULAO', 'jimler.tagulaao@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530200', 'Mark Steaven', 'FOLLANTE', 'mark.follante@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530238', 'Janica Mae Vergara', 'SERGIO', 'janica.sergio@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530334', 'Jan Mikel Gabriel', 'REJANO', 'jan.rejano@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530408', 'Joyce Dagoy', 'AGULLO', 'joyce.agullo@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530420', 'Aldrin Flores', 'MARCAIDA', 'aldrin.marcaida@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530429', 'Prince Alex Gaudiano', 'PEPITO', 'prince.pepito@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530438', 'Kaye Patricia F', 'ALMOETE', 'kaye.almoete@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530443', 'Niña Jade Crisostomo', 'IGNACIO', 'nina.ignacio@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530444', 'Ava Mae San Jose', 'PEREZ', 'ava.perez@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530445', 'Eroel Jhon Dalapa', 'ALTAGRACIA', 'eroel.altagracia@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530446', 'Vega Villamor', 'LEGASPI', 'vega.legaspi@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530449', 'Algianne Mardee Mujeres', 'PEREZ', 'algianne.perez@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530472', 'Renchelle Nota', 'DIMAYMAY', 'renchelle.dimaymay@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530504', 'Joanna Rhacia Diana', 'RIVERA', 'joanna.rivera@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530508', 'Clover Baluyos', 'DEL ROSARIO', 'clover.delrosario@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530528', 'Princes Joy Distor', 'BUHAT', 'princes.buhat@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530590', 'Kyle Aizhen', 'RIVERA', 'kyle.rivera@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530597', 'James Erik Ferranco', 'SALANGO', 'james.salango@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202531066', 'Geciel', 'SALAMODING', 'geciel.salamoding@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530601', 'Rayver Basas', 'ARPON', 'rayver.arpon@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530603', 'Liam Patrick Claudio', 'LOYOLA', 'liam.loyola@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530740', 'Princess Helena Garcia', 'CRUZ', 'princess.cruz@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530754', 'Brian Gabriel Gabriel', 'RAMOS', 'brian.ramos@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530813', 'Althea Divine Amistad', 'OCHEA', 'althea.ochea@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530852', 'Noella Marjolaine Tapauan', 'MATATQUIN', 'noella.matatquin@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202531033', 'Djoahna Marie Etcuban', 'SODELA', 'djoahna.sodela@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530870', 'Angelica Hipolito', 'SORIA', 'angelica.soria@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530885', 'John Alexciss Rublico', 'CANALES', 'john.canales@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530896', 'Christine Guray', 'CLUTARIO', 'christine.clutario@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530903', 'Charlie Kate Operana', 'TOBI', 'charlie.tobi@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530950', 'Joaquin Angelo Vargas', 'SONEJA', 'joaquin.soneja@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active'),
('202530961', 'Edelhey Niña Quinlog', 'SISON', 'edelhey.sison@student.pupu.edu.ph', 'BSHM', 'First Year', 'Section 1', 'Active');

CREATE TABLE IF NOT EXISTS admins (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO admins (username, password) 
VALUES ('admin', 'admin');